# Generated by Django 5.0.1 on 2024-02-07 02:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("d01_fn_api_view", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="category",
        ),
        migrations.AddField(
            model_name="products",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 7, 2, 55, 45, 958809)
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
