# Generated by Django 5.0.1 on 2024-02-08 03:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=255)),
                (
                    "author",
                    models.CharField(
                        max_length=150, verbose_name="Person who create a comment."
                    ),
                ),
                (
                    "up_votes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Number of up-votes for a comment."
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
