# Generated by Django 5.0.1 on 2024-02-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d04_api_viewsets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
